= Create a Kafka service

Apply the following object on your namespace, as specified by its YAML description.

.Example to create a Kafka instance
[source,yaml]
----
apiVersion: appcat.vshn.io/v1
kind: ExoscaleKafka
metadata:
  name: my-kafka-example # <1>
  namespace: my-namespace # <2>
spec:
  parameters:
    service:
      kafkaSettings:
        connections_max_idle_ms: 60000 # <3>
      zone: ch-dk-2 # <4>
    size:
      plan: startup-2 # <5>
  writeConnectionSecretToRef:
    name: kafka-creds # <6>
----
<1> Instance name
<2> The namespace where the object will be created.
<3> Specify custom Kafka settings [optional]
<4> The Exoscale zone to use, see xref:references/clouds.adoc#_regions[list of regions]
<5> See https://products.docs.vshn.ch/products/appcat/exoscale_dbaas.html#_kafka[reference] for a list of plans
<6> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-exoscale-v1-exoscalekafka[API Reference]

== Inspect your new Kafka service

[source,bash]
----
$ oc get exoscalekafka
NAME               PLAN         ZONE      VERSION   READY   CONNECTION-SECRET   AGE
my-kafka-example   startup-2    ch-dk-2   3.2       True    kafka-creds         15m
----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

NOTE: The provisioning time of Kafka can be quite long, and it might take up to 15 minutes for the instance to be ready.

== Find the connection details

The connection details are stored in a secret. You can retrieve them with the following command:

[source,bash]
----
$ oc get secrets kafka-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

include::page$references/secrets.adoc[tag=kafka]
