= Exoscale DBaaS - Apache Kafka

This section provides documentation related to the https://www.exoscale.com/dbaas/kafka/[Exoscale DBaaS Managed Apache Kafka^] service in the VSHN Application Catalog.

Learn more about this service, including its pricing, in our https://products.docs.vshn.ch/products/appcat/exoscale_dbaas.html[product documentation site].

TIP: Get started and xref:exoscale-dbaas/kafka/create.adoc[create an Apache Kafka instance].

== Notes

Some important notes about this service:

* Connections are only possible using authenticated TLS encrypted connections.
* The service uses a self-signed certificate which can be verified using the CA certificate provided in the connection secret (Key `ca.crt`).

== Links

* https://kafka.apache.org/[Apache Kafka^]
* xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-exoscale-v1-exoscalekafka[VSHN Application Catalog API reference]
* https://community.exoscale.com/documentation/dbaas/managed-apache-kafka/[Exoscale documentation^]
* https://docs.aiven.io/docs/products/kafka[Aiven documentation^]
