= Exoscale DBaaS - MySQL

This section provides documentation related to the https://www.exoscale.com/dbaas/mysql/[Exoscale DBaaS Managed MySQL^] service in the VSHN Application Catalog.

Learn more about this service, including its pricing, in our https://products.docs.vshn.ch/products/appcat/exoscale_dbaas.html[product documentation site].

TIP: Get started and xref:exoscale-dbaas/mysql/create.adoc[create a MySQL instance].

== Notes

Some important notes about this service:

* Connections are only possible using authenticated TLS encrypted connections.
* The service uses a self-signed certificate which can be verified using the CA certificate provided in the connection secret (key `ca.crt`).

== Links

* https://www.mysql.com/[MySQL^]
* xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-exoscale-v1-exoscalemysql[VSHN Application Catalog API reference]
* https://community.exoscale.com/documentation/dbaas/managed-mysql/[Exoscale documentation^]
* https://docs.aiven.io/docs/products/mysql[Aiven documentation^]
