= Create a Redis service

Apply the following object on your namespace, as specified by its YAML description.

.Example to create a Redis instance
[source,yaml]
----
apiVersion: exoscale.appcat.vshn.io/v1
kind: ExoscaleRedis
metadata:
  name: my-redis-example # <1>
  namespace: my-namespace # <2>
spec:
  parameters:
    service:
      redisSettings:
        maxmemory_policy: noeviction # <3>
      zone: ch-dk-2 # <4>
    size:
      plan: hobbyist-2 # <5>
  writeConnectionSecretToRef:
    name: redis-creds # <6>
----
<1> Instance name
<2> The namespace where the object will be created.
<3> Specify custom Redis settings [optional]
<4> The Exoscale zone to use, see xref:references/clouds.adoc#_regions[list of regions]
<5> See https://products.docs.vshn.ch/products/appcat/exoscale_dbaas.html#_redis[reference] for a list of plans
<6> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-exoscale-v1-exoscaleredis[API Reference]

== Inspect your new Redis service

[source,bash]
----
$ oc get exoscaleredis
NAMESPACE      NAME               PLAN         ZONE      READY   CONNECTION-SECRET   AGE
my-namespace   my-redis-example   hobbyist-2   ch-dk-2   True    redis-creds         2m
----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

== Find the connection details

The connection details are stored in a secret. You can retrieve them with the following command:

[source,bash]
----
$ oc get secrets redis-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

include::page$references/secrets.adoc[tag=redis]

NOTE: Exoscale Redis supports connection via TLS.
The certificates are signed by Let's Encrypt, so no ca.crt file required.
