= Create a PostgreSQL service

Apply the following object on your namespace, as specified by its YAML description.

.Example to create a PostgreSQL instance
[source,yaml]
----
apiVersion: exoscale.appcat.vshn.io/v1
kind: ExoscalePostgreSQL
metadata:
  name: my-postgres-example # <1>
  namespace: my-namespace # <2>
spec:
  parameters:
    backup:
      timeOfDay: "12:00:00" # <3>
    service:
      zone: ch-dk-2 # <4>
      majorVersion: "14" # <5>
      pgSettings:
        timezone: Europe/Zurich # <6>
    size:
      plan: hobbyist-2 # <7>
  writeConnectionSecretToRef:
    name: postgres-creds # <8>
----
<1> Instance name
<2> The namespace where the object will be created
<3> Specify backup time of day
<4> The Exoscale zone to use, see xref:references/cloud-zones.adoc#_regions[list of regions]
<5> PostgreSQL version
<6> Specify custom PostgreSQL settings [optional]
<7> See https://products.docs.vshn.ch/products/appcat/exoscale_dbaas.html#_postgresql[reference] for a list of plans
<8> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please refer to the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-exoscale-v1-exoscalepostgresql[API Reference]

== Inspect your new PostgreSQL service

[source,bash]
----
$ oc get exoscalepostgresql
NAMESPACE      NAME                  PLAN         ZONE      READY   CONNECTION-SECRET   AGE
my-namespace   my-postgres-example   hobbyist-2   ch-dk-2   True    postgres-creds      5m
----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

== Find the connection details

The connection details are stored in a secret. You can retrieve them with the following command:

[source,bash]
----
$ oc get secrets postgres-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

include::page$references/secrets.adoc[tag=postgres]
