= Create a PostgreSQL service

AppCat allows DevOps engineers to quickly provision a PostgreSQL instance.

== Create a PostgreSQL service

include::user:ROOT:partial$login-in-terminal.adoc[]

. Apply the following object on your namespace, as specified by its YAML description.
+
.Example to create a PostgreSQL instance
[source,yaml]
----
apiVersion: appcat.vshn.io/v1
kind: ExoscalePostgreSQL
metadata:
  name: my-postgres-example <1>
  namespace: my-namespace <2>
spec:
  parameters:
    backup:
      timeOfDay: "12:00:00" <3>
    service:
      zone: ch-dk-2 <4>
      majorVersion: "14" <5>
      pgSettings:
        timezone: Europe/Zurich <6>
    size:
      plan: hobbyist-2 <7>
  writeConnectionSecretToRef:
    name: postgres-creds <8>
----
<1> Instance name
<2> The namespace where the object will be created
<3> Specify backup time of day
<4> The Exoscale zone to use, see xref:references/clouds.adoc#_regions[list of regions]
<5> PostgreSQL version
<6> Specify custom PostgreSQL settings [optional]
<7> See https://products.docs.vshn.ch/products/appcat/exoscale_dbaas.html#_postgresql[reference] for a list of plans
<8> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-v1-exoscalepostgresql[API Reference]

== Get information about your new PostgreSQL instance

[source,bash]
----
$ oc get exoscalepostgresql
NAMESPACE      NAME                  PLAN         ZONE      READY   CONNECTION-SECRET   AGE
my-namespace   my-postgres-example   hobbyist-2   ch-dk-2   True    postgres-creds      5m
----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

== Get the credentials to access the instance

[source,bash]
----
$ oc get secrets postgres-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
data:
  POSTGRESQL_DB: ZGVmYXVsdGRi <1>
  POSTGRESQL_HOST: bXktcG9zdGdyZXMtZXhhbXBsZS1leG9zY2FsZS0xMjM0LmFpdmVuY2xvdWQuY29tCg== <2>
  POSTGRESQL_PASSWORD: QVZOU19zb21lc3VwZXJzZWNyZXRwdwo= <3>
  POSTGRESQL_PORT: MjE2OTk= <4>
  POSTGRESQL_URL: cG9zdGdyZXM6Ly9hdm5hZG1pbjpBVk5TX3NvbWVzdXBlcnNlY3JldHB3QG15LXBvc3RncmVzLWV4YW1wbGUtZXhvc2NhbGUtMTIzNC5haXZlbmNsb3VkLmNvbToyMTY5OS9kZWZhdWx0ZGI/c3NsbW9kZT1yZXF1aXJlCg== <5>
  POSTGRESQL_USER: YXZuYWRtaW4= <6>
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCkhleFZhbHVlcwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== <7>
----
<1> Database name
<2> Host to connect to
<3> Password
<4> Port
<5> URL containing all necessary information to connect to the instance
<6> Username
<7> ca.crt to use when using `sslmode=verify-full`

IMPORTANT: All data fields are Base64-encoded, like any other https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/[Kubernetes secret].
