= Create a Redis service

AppCat allows DevOps engineers to quickly provision a redis instance.

== Create a redis service

include::user:ROOT:partial$login-in-terminal.adoc[]

. Apply the following object on your namespace, as specified by its YAML description.
+
.Example to create an Object Storage bucket
[source,yaml]
----
apiVersion: appcat.vshn.io/v1
kind: ExoscaleRedis
metadata:
  name: my-redis-example <1>
  namespace: my-namespace <2>
spec:
  parameters:
    service:
      redisSettings:
        maxmemory_policy: noeviction <3>
      zone: ch-dk-2 <4>
    size:
      plan: hobbyist-2 <5>
  writeConnectionSecretToRef:
    name: redis-creds <6>
----
<1> Instance name: *don't just copy/paste this code, remember to choose your own name here!*
<2> The namespace where the object will be created.
<3> Specify custom redis settings
<4> The exoscale zone to use
<5> See xref:redis/reference.adoc[reference] for list of plans
<6> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

== Get information about your new redis instance

[source,bash]
----
$ oc get exoscaleredis
NAMESPACE      NAME               PLAN         ZONE      READY   CONNECTION-SECRET   AGE
my-namespace   my-redis-example   hobbyist-2   ch-dk-2   True    redis-creds         2m
----

If you see "True" in the READY column, it means the instance is provisioned and ready to use.

== Get the credentials to access the instance

[source,bash]
----
$ oc get secrets redis-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
data:
  REDIS_HOST: MTI3LjAuMC4xCg== <1>
  REDIS_PASSWORD: QVZOU19zb21lc3VwZXJzZWNyZXRwdwo= <2>
  REDIS_PORT: MjE3MDA= <3>
  REDIS_URL: cmVkaXNzOi8vZGVmYXVsdDpBVk5TX3NvbWVzdXBlcnNlY3JldHB3QDEyNy4wLjAuMToyMTcwMAo= <4>
  REDIS_USERNAME: ZGVmYXVsdA== <5>
----
<1> Host to connect to
<2> Password
<3> Port to use
<4> URL containing all necessary information to connect to the instance
<5> Username

IMPORTANT: All data fields are Base64-encoded, like any other https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/[Kubernetes secret].
