# ---------- STEP 1 ----------
# Index the project files
FROM ghcr.io/vshn/antora-indexer-cli:1.15 as indexer

COPY playbook.yml /playbook.yml
RUN \
    mkdir /index && \
    antora-indexer --playbook / --write files --output /index/files.json && \
    antora-indexer --playbook / --write index --output /index/lunr.json

# ---------- STEP 2 ----------
# Docker image only containing the search engine and the freshly built index
FROM ghcr.io/vshn/embedded-search-engine:1.10

# Copy the index of the search engine
COPY --from=indexer /index/files.json /site/index/files.json
COPY --from=indexer /index/lunr.json /site/index/lunr.json
