= Nextcloud Collabora

Collabora Online is a powerful LibreOffice-based online office suite with collaborative editing, which supports all major document, spreadsheet and presentation file formats and works in all modern browsers. It allows you to view and edit office documents directly in your Nextcloud.

== Create a Collabora service

Extend Your Nextcloud instance with Collabora Online. Apply the following object on your namespace, as specified by its YAML description.

[source,yaml]
-----
(...)
spec:
  parameters:
    service:
      collabora:
        enabled: true
        fqdn: my-collabora.example.com # <1>
        version: 25.04.1.1.1           # <2>
-----

<1> Your full qualified domain name. For our Appuio Cloud offering, You can learn more how to configure your DNS settings https://docs.appuio.cloud/user/how-to/getting-a-certificate.html[here].
<2> Specifies the Collabora Online image tag to use for deployment. By default, the latest version tested by VSHN will be used. You can override it with a specific version tag from the official https://hub.docker.com/r/collabora/code/tags[Docker Hub repository].

This will create a Collabora service with the specified FQDN and version. The Collabora service will be available at `https://my-collabora.example.com` and autoconfigured in your Nextcloud instance.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-vshn-v1-vshnnextcloud[API Reference]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
