= Create a Opensearch service

AppCat allows DevOps engineers to quickly provision an Opensearch instance.

== Create an Opensearch service

include::user:ROOT:partial$login-in-terminal.adoc[]

. Apply the following object on your namespace, as specified by its YAML description.
+
.Example to create an Opensearch instance
[source,yaml]
----
apiVersion: exoscale.appcat.vshn.io/v1
kind: ExoscaleOpensearch
metadata:
  name: my-opensearch-example <1>
  namespace: my-namespace <2>
spec:
  parameters:
    backup:
      timeOfDay: "12:00:00" <3>
    service:
      zone: ch-dk-2 <4>
      majorVersion: "2" <5>
      opensearchSettings:
        http_max_content_length: 12345 <6>
    size:
      plan: hobbyist-2 <7>
  writeConnectionSecretToRef:
    name: opensearch-creds <8>
----
<1> Instance name
<2> The namespace where the object will be created
<3> Specify backup time of day
<4> The Exoscale zone to use, see xref:references/clouds.adoc#_regions[list of regions]
<5> Opensearch major version
<6> Specify custom Opensearch settings [optional] https://docs.aiven.io/docs/products/opensearch/reference/advanced-params.html#opensearch[full list of params]
<7> See https://products.docs.vshn.ch/products/appcat/exoscale_dbaas.html#_opensearch[reference] for a list of plans
<8> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-v1-exoscaleopensearch[API Reference]

== Get information about your new Opensearch instance

[source,bash]
----
$ kubectl get exoscaleopensearches.exoscale.appcat.vshn.io
NAME    SYNCED   READY   CONNECTION-SECRET                        AGE
test1   True     True    opensearch-creds   8m21s

----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

== Get the credentials to access the instance

[source,bash]
----
$ oc get secrets opensearch-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-creds
data:
  OPENSEARCH_DASHBOARD_URI: aHR(...)0Mw== <1>
  OPENSEARCH_PASSWORD: QVZ(...)0pS <2>
  OPENSEARCH_URI: aHR(..)ak5 <3>
  OPENSEARCH_USER: YXZ(...)aW4= <4>

----
<1> Dashboards URL
<2> Password
<3> API URL
<4> User

IMPORTANT: All data fields are Base64-encoded, like any other https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/[Kubernetes secret].
