= VSHN AppCat Documentation

image::vshn-appcat.svg[VSHN AppCat,400,link=https://www.appcat.ch/]

Welcome to the VSHN Application Catalog (AppCat) Documentation Documentation! AppCat allows DevOps engineers to quickly and safely provision cloud services.

IMPORTANT: At this time AppCat only serves selected https://portal.appuio.cloud/zones[APPUiO Cloud zones]. Please check the availability of your desired feature in the tables below.

== Available Services

The table below provides a quick overview of the various AppCat services and their availability across APPUiO Cloud zones and service providers. To list all available services directly in the cluster check out our xref:apiserver/how-to.adoc[AppCat API Server] documentation page.

[cols="1,1,1,1"]
|===
.2+.^h|Service
.2+.^h|Service Provider
2+^h| Zones

h|`cloudscale-lpg-2`
h|`exoscale-ch-gva-2-0`


.2+|Object Storage
| cloudscale.ch
^|✅
^|✅

|Exoscale
^|✅
^|✅

|===

Get started with xref:object-storage/create.adoc[Create an Object Storage Bucket].

=== Exoscale DBaaS

[cols="1,1,1",options="header"]
|===
|Database
|cloudscale.ch
|Exoscale

|MySQL
|❌
|✅ xref:exoscale-dbaas/mysql/index.adoc[More infos]

|PostgreSQL
|❌
|✅ xref:exoscale-dbaas/postgresql/index.adoc[More infos]

|Redis
|❌
|✅ xref:exoscale-dbaas/redis/index.adoc[More infos]

|Kafka
|❌
|✅ xref:exoscale-dbaas/kafka/index.adoc[More infos]

|OpenSearch
|❌
|✅ xref:exoscale-dbaas/opensearch/index.adoc[More infos]

|===

=== Managed by VSHN

[cols="1,1,1",options="header"]
|===
|Database
|cloudscale.ch
|Exoscale


|PostgreSQL
|✅ xref:vshn-managed/postgresql/index.adoc[More infos]
|❌

|Redis
|✅ xref:vshn-managed/redis/index.adoc[More infos]
|❌


|===

Get started with xref:vshn-managed/postgresql/create.adoc[Create a PostgreSQL instance].
Get started with xref:vshn-managed/redis/create.adoc[Create a Redis instance].

