= VSHN Application Catalog Documentation

image::appuio-cloud.svg[APPUiO Cloud,400,link=https://www.appuio.ch/en/offering/cloud/]

Welcome to the AppCat Documentation! AppCat allows DevOps engineers to quickly and safely provision cloud services.

IMPORTANT: At this time AppCat only serves selected https://portal.appuio.cloud/zones[APPUiO Cloud zones]. Please check the availability of your desired feature in the tables below.

== Available Services

The table below provides a quick overview of the various AppCat services and their availability across APPUiO Cloud zones and service providers.

[cols="1,1,1,1"]
|===
.2+.^h|Service
.2+.^h|Service Provider
2+^h| Zones

h|`cloudscale-lpg-2`
h|`exoscale-ch-gva-2-0`


.2+|Object Storage
| cloudscale.ch
^|✅
^|✅

|Exoscale
^|✅
^|✅

|===

Get started with xref:object-storage/create.adoc[Create an Object Storage Bucket].

=== Exoscale DBaaS

[cols="1,1,1",options="header"]
|===
|Database
|cloudscale.ch
|Exoscale

|MySQL
|❌
|✅ xref:exoscale-dbaas/mysql/index.adoc[More infos]

|PostgreSQL
|❌
|✅ xref:exoscale-dbaas/postgresql/index.adoc[More infos]

|Redis
|❌
|✅ xref:exoscale-dbaas/redis/index.adoc[More infos]

|Kafka
|❌
|✅ xref:exoscale-dbaas/kafka/index.adoc[More infos]

|OpenSearch
|❌
|✅ xref:exoscale-dbaas/opensearch/index.adoc[More infos]

|===

=== Vshn DBaaS

[cols="1,1,1",options="header"]
|===
|Database
|cloudscale.ch
|Exoscale


|PostgreSQL
|✅ xref:vshn-managed/postgresql/index.adoc[More infos]
|❌ (Coming soon)


|===

Get started with xref:vshn-managed/postgresql/create.adoc[Create a PostgreSQL instance].
