= Create an Object Storage Bucket

AppCat allows DevOps engineers to quickly provision S3-compatible Object Storage Buckets in various environments.

== Create a Bucket

include::user:ROOT:partial$login-in-terminal.adoc[]

. Apply the following object on your namespace, as specified by its YAML description.
+
.Example to create an Object Storage bucket
[source,yaml]
----
apiVersion: appcat.vshn.io/v1
kind: ObjectBucket
metadata:
  name: my-cool-bucket
  namespace: my-namespace <1>
spec:
  parameters:
    bucketName: my-bucket-change-name <2>
    region: rma <3>
  writeConnectionSecretToRef:
    name: objectbucket-creds <4>
----
<1> The namespace where the object will be created.
<2> Bucket name: *don't just copy/paste this code, remember to choose your own name here!*
<3> The bucket's region depends on the selected Provider, see TODO: for more details
<4> Secret where the connection details are provisioned. This secret shouldn't exist at this time.
+
IMPORTANT: Object Storage Bucket names must be unique across providers. Make sure to choose a name with prefixes and other guards, to prevent any issue during the creation of the bucket. No error message is returned if the bucket cannot be created.

. Get information about your new bucket object.
+
[source,bash]
----
$ oc get objectbucket
NAME               READY   CONNECTION-SECRET    AGE
my-cool-bucket     True    objectbucket-creds   5s
----
+
If you see the "True" value in the READY column, it means that your bucket is provisioned and ready to use.
+
IMPORTANT: If your object bucket doesn't get the state ready after a while, try to delete the bucket and re-create it with a different name.

. Get the required secrets to use your bucket from other applications.
+
[source,bash]
----
$ oc get secrets objectbucket-creds -oyaml
----
The complete specification of the generated secret object can be found in the xref:object-storage/secrets.adoc[secrets page].

. Check the bucket status
+
[source,bash]
----
$ oc describe objectbucket my-cool-bucket
Name:         my-cool-bucket
Namespace:    a-demo-project
# …
Status:
  Conditions:
    Last Transition Time:  2022-09-02T07:38:40Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Connection Details:
    Last Published Time:  2022-09-02T07:38:40Z
Events:
  Type     Reason                      Age                From                                                             Message
  ----     ------                      ----               ----                                                             -------
  Warning  ConfigureCompositeResource  12m (x2 over 12m)  offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot apply composite resource: cannot patch object: Operation cannot be fulfilled on xobjectbuckets.appcat.vshn.io "my-cool-bucket-2ds78": the object has been modified; please apply your changes to the latest version and try again
  Normal   ConfigureCompositeResource  12m (x8 over 12m)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully applied composite resource
  Normal   BindCompositeResource       12m (x6 over 12m)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Composite resource is not yet ready
  Normal   BindCompositeResource       12m (x2 over 12m)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully bound composite resource
  Normal   PropagateConnectionSecret   12m                offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully propagated connection details from composite resource
----
