= Restores

IMPORTANT: *Restore operation will create a new MariaDB instance with new credentials*

By default, every mariadb instance creates a backup once a day or at the time you specified.

Please visit the (xref:vshn-managed/mariadb/backup.adoc[Backup documentation] for more information.

You can list all the backups that are available with the following command:

[source,bash]
----
kubectl -n <your-namespace> get vshnmariadb

BACKUP ID   DATABASE INSTANCE   BACKUP TIME
6678cecd    mariadb-app1-prod     2024-01-05T08:11:02Z
6df7d405    mariadb-app1-prod     2024-01-05T07:30:05Z
4bb23139    mariadb-app2-prod     2024-01-05T12:29:05Z
e5164ada    mariadb-app2-prod     2024-01-05T12:33:02Z
----

This will list all the backup available to you.
You can then restore the backup to a new instance, by using the following restore configuration:

[source,yaml]
----
apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNMariaDB
metadata:
  name: mariadb-app2-prod
  namespace: <your-namespace>
spec:
  parameters:
    ...
    restore:
      claimName: mariadb-app1-prod <1>
      backupName: e5164ada <2>
    ...
----
<1> The claimName of the original mariadb instance to restore from
<2> The Backup ID which you want to restore

This configuration will spin up a new mariadb instance and will restore the specified backup to your instance.
In the example above, the new mariadb instance will be called `mariadb-app2-prod` and will be running the restored data from the mariadb instance `mariadb-app1-prod` using the backup `e5164ada` tat was taken at `2024-01-05T12:33:02Z`
