= Create a Redis service

AppCat allows DevOps engineers to quickly provision a Redis instance.

== Create a Redis service

include::user:ROOT:partial$login-in-terminal.adoc[]

. Apply the following object on your namespace, as specified by its YAML description.
+
.Example to create a PostgreSQL instance
[source,yaml]
----
apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNRedis
metadata:
  name: redis-app1-prod <1>
  namespace: prod-app <2>
spec:
  parameters:
    service:
      version: "7.0" <3>
      redisSettings: | <4>
        activedefrag yes
    size: <5>
      plan: standard-2
  writeConnectionSecretToRef:
    name: redis-creds <6>
----
<1> Instance name
<2> The namespace where the object will be created
<3> Redis version
<4> Specify custom Redis settings [optional]
<5> Size of the Redis instance. See xref:vshn-managed/redis/plans.adoc[Plans and Sizing] for more information.
<6> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-vshn-v1-vshnredis[API Reference]

== Get information about your new Redis instance

[source,bash]
----
$  oc get vshnredis.vshn.appcat.vshn.io
NAME              SYNCED   READY   CONNECTION-SECRET   AGE
pgsql-app1-prod   True     True    redis-creds         3m32s
----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

== Get the credentials to access the instance

[source,bash]
----
$ oc get secrets redis-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

include::appcat:ROOT:page$references/secrets.adoc[tag=redis]
