= Create a PostgreSQL service

AppCat allows DevOps engineers to quickly provision a PostgreSQL instance.

== Create a PostgreSQL service

include::user:ROOT:partial$login-in-terminal.adoc[]

. Apply the following object on your namespace, as specified by its YAML description.
+
.Example to create a PostgreSQL instance
[source,yaml]
----
apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNPostgreSQL
metadata:
  name: pgsql-app1-prod <1>
  namespace: prod-app <2>
spec:
  parameters:
    service:
      majorVersion: "15" <3>
      pgSettings:
        timezone: Europe/Zurich <4>
    size: <5>
      cpu: "600m"
      memory: "3500Mi"
      requests: <6>
        cpu: "300m"
        memory: "1000Mi"
      disk: "80Gi"
    scheduling:
      nodeSelector:
        appuio.io/node-class: "plus" <7>
  writeConnectionSecretToRef:
    name: postgres-creds <8>
----
<1> Instance name
<2> The namespace where the object will be created
<3> PostgreSQL version
<4> Specify custom PostgreSQL settings [optional]
<5> CPU, memory and disk configurations
<6> CPU and memory requests configuration [optional]
<7> Specify the node class for the instance [optional]
<8> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-vshn-v1-vshnpostgresql[API Reference]


NOTE: The PostgreSQL instance will be scheduled on the platforms default node class. You can override this by setting the `spec.parameters.scheduling.nodeSelector` field accordingly. For more information see https://docs.appuio.cloud/user/references/node-classes.html[Node Classes]

NOTE: By default the resource requests and limits are set to the values defined in `spec.parameters.size.cpu` and `spec.parameters.size.memory`. If you want to explicitely set resource requests that are lower than the limit you need to define them in `spec.parameters.size.requests`.

=== Sidecar Overhead and Fair-Use Policy

Each PostgreSQL Standalone instance has following overhead:

* CPU: 364m
* Memory: 704Mi

These are for various sidecar containers that run alongside the actual PostgreSQL instance.
These containers handle connection pooling, metrics and other internal functionality.

NOTE: Please be aware that https://docs.appuio.cloud/user/explanation/fair-use-policy.html[Fair Use Policy] applies to all AppCat Services by VSHN.
When chosing memory and CPU for your instance please keep the overhead in mind.

== Get information about your new PostgreSQL instance

[source,bash]
----
$  kubectl get vshnpostgresqls.vshn.appcat.vshn.io
NAME              SYNCED   READY   CONNECTION-SECRET   AGE
pgsql-app1-prod   True     True    postgres-creds      6m14s
----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

== Get the credentials to access the instance

[source,bash]
----
$ oc get secrets postgres-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

include::appcat:ROOT:page$references/secrets.adoc[tag=postgres]
