= Create a PostgreSQL service

Apply the following object on your namespace, as specified by its YAML description.

.Example to create a PostgreSQL instance
[source,yaml]
----
apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNPostgreSQL
metadata:
  name: pgsql-app1-prod # <1>
  namespace: prod-app # <2>
spec:
  parameters:
    service:
      majorVersion: "16" # <3>
      pgBouncerSettings: # <4>
        pgbouncer:
          admin_users: postgres
      pgSettings:
        timezone: Europe/Zurich # <5>
    size: # <6>
      plan: plus-4
    backup: # <7>
      schedule: "30 23 * * *"
      retention: 12
  writeConnectionSecretToRef:
    name: postgres-creds # <8>
----
<1> Instance name
<2> The namespace where the object will be created
<3> PostgreSQL version. For supported versions, see our https://products.vshn.ch/appcat/postgresql.html#_supported_versions[product docs^]
<4> Specify additional configuration to the pgBouncer instance [optional]. See https://www.pgbouncer.org/config.html[documentation]
<5> Specify custom PostgreSQL settings [optional]
<6> Size of the PostgreSQL instance. See xref:vshn-managed/postgresql/plans.adoc[Plans and Sizing] for more information.
<7> Backup configuration, `schedule` standard cron: https://en.wikipedia.org/wiki/Cron, `retention` field specify how many backups should be kept
<8> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-vshn-v1-vshnpostgresql[API Reference]


== Inspect your new PostgreSQL service

[source,bash]
----
$  kubectl get vshnpostgresqls.vshn.appcat.vshn.io
NAME              SYNCED   READY   CONNECTION-SECRET   AGE
pgsql-app1-prod   True     True    postgres-creds      6m14s
----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

== Find the connection details

The connection details are stored in a secret. You can retrieve them with the following command:

[source,bash]
----
$ oc get secrets postgres-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

include::page$references/secrets.adoc[tag=postgres]
