= Create a PostgreSQL service

Apply the following object on your namespace, as specified by its YAML description.

.Example to create a PostgreSQL instance
[source,yaml]
----
apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNPostgreSQL
metadata:
  name: pgsql-app1-prod # <1>
  namespace: prod-app # <2>
spec:
  parameters:
    service:
      majorVersion: "15" # <3>
      pgBouncerSettings: # <4>
        admin_users: postgres
      pgSettings:
        timezone: Europe/Zurich # <5>
    size: # <6>
      plan: plus-4
    backup: # <7>
      schedule: "30 23 * * *"
      retention: 12
  writeConnectionSecretToRef:
    name: postgres-creds # <8>
----
<1> Instance name
<2> The namespace where the object will be created
<3> PostgreSQL version
<4> Specify additional configuration to the pgBouncer instance [optional]. See https://www.pgbouncer.org/config.html[documentation]
<5> Specify custom PostgreSQL settings [optional]
<6> Size of the PostgreSQL instance. See xref:vshn-managed/postgresql/plans.adoc[Plans and Sizing] for more information.
<7> Backup configuration, `schedule` standard cron: https://en.wikipedia.org/wiki/Cron, `retention` field specify how many backups should be kept
<8> Secret where the connection details are provisioned. This secret shouldn't exist before creation.

NOTE: To get more information about all available configuration options, please see the xref:references/crds.adoc#k8s-api-github-com-vshn-component-appcat-apis-vshn-v1-vshnpostgresql[API Reference]


== Inspect your new PostgreSQL service

[source,bash]
----
$  kubectl get vshnpostgresqls.vshn.appcat.vshn.io
NAME              SYNCED   READY   CONNECTION-SECRET   AGE
pgsql-app1-prod   True     True    postgres-creds      6m14s
----

When you see `True` in the READY column, it means the instance is provisioned and ready to use.

== Find the connection details

The connection details are stored in a secret. You can retrieve them with the following command:

[source,bash]
----
$ oc get secrets postgres-creds -o yaml
----

The output of the command above is a secret specification with the following structure:

include::page$references/secrets.adoc[tag=postgres]

== Create a database with a specific locale

The default locale when databases are created is `C.UTF-8`.
If an application needs a specific locale that is different, then you can do the following:

.Create a user and database in the instance
[source,yaml]
----
apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNPostgreSQL
metadata:
  name: pgsql-app1-prod
  namespace: prod-app
spec:
  parameters:
    service:
      access:
        - user: myapp <1>
  writeConnectionSecretToRef:
    name: postgres-creds
----
<1> This will create a user and a database `myapp`

After that, we create a pod that will re-create the database with the desired settings.

.Run a pod with SQL commands to create custom database
[source,yaml]
----
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  namespace: prod-app
spec:
  containers:
  - name: postgres
    image: postgres:15
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - /bin/sh
      - -c
    args:
      - PGPASSWORD=$POSTGRESQL_PASSWORD psql "sslmode=verify-ca sslrootcert=/etc/secret-volume/ca.crt host=$POSTGRESQL_HOST port=$POSTGRESQL_PORT dbname=$POSTGRESQL_DB" -U $POSTGRESQL_USER -c "drop database if exists $DBNAME with (force)"
        -c "create database $DBNAME LC_COLLATE='C' LC_CTYPE='C' ENCODING='UTF-8' TEMPLATE='template0'"
    envFrom:
      - secretRef:
          name: postgres-creds # <1>
    env:
      - name: DBNAME
        value: myapp # <2>
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
  volumes:
  - name: secret-volume
    secret:
      defaultMode: 0600
      secretName: postgres-creds # <1>
  restartPolicy: OnFailure

----
<1> The pod will use the secret to connect to the instance. Has to match the `writeConnectionSecretToRef` field of the instance.
<2> Change the name to the database name you want

You can use this `postgres-client` pod as a template for any SQL commands you want to run against your AppCat VSHNPostgreSQL instance.
