= How to use an AppCat PostgreSQL instance

The YAML code below creates two objects: a `VSHNPostgreSQL` instance and a pod accessing it to show information about the instance.
The latter references the `postgres-creds` secret that will contain the access keys required to connect to the instance.

[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: app1-prod
  labels:
    name: app1-prod
---
apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNPostgreSQL
metadata:
  name: postgresql-prod
  namespace: app1-prod
spec:
  parameters:
    service:
      majorVersion: "15"
    backup:
      schedule: '0 22 * * *'
  writeConnectionSecretToRef:
    name: postgres-creds-connection
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  namespace: app1-prod
spec:
  containers:
  - name: postgres
    image: postgres:15
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - /bin/sh
      - -c
    args:
      - PGPASSWORD=$POSTGRESQL_PASSWORD psql "sslmode=verify-ca sslrootcert=/etc/secret-volume/ca.crt host=$POSTGRESQL_HOST port=$POSTGRESQL_PORT dbname=$POSTGRESQL_DB" -U $POSTGRESQL_USER -l
    envFrom:
      - secretRef:
          name: postgres-creds-connection
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
  volumes:
  - name: secret-volume
    secret:
      defaultMode: 0600
      secretName: postgres-creds-connection
  restartPolicy: OnFailure
----

== Debug instance by yourself

You can easily check what happened during creation by checking the status fields. PostgreSQL by VSHN is composed from many resources, responsible for
cluster creation, bucket creation, backups and uploads to cloud, each of those components might break or be misconfigured (f.e typo). You can check what happend by running

```
# example assumes reuse of names and namespace from example above
kubectl -n app1-prod describe vshnpostgresqls.vshn.appcat.vshn.io postgresql-prod 
```

Example output looks as follows:

```
Status:
  Certificate Debug:
    Last Transition Time:  2023-02-13T15:11:44Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-13T15:11:42Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
  Conditions:
    Last Transition Time:  2023-02-13T15:11:39Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-02-13T15:12:21Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Connection Details:
    Last Published Time:  2023-02-13T15:12:21Z
  Local CA Debug:
    Last Transition Time:  2023-02-13T15:11:43Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-13T15:11:41Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
  Namespace Debug:
    Last Transition Time:  2023-02-13T15:11:41Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-13T15:11:41Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
  Network Policy Debug:
    Last Transition Time:  2023-02-13T15:11:45Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-13T15:11:43Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
  Pgcluster Debug:
    Last Transition Time:  2023-02-13T15:11:48Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-13T15:11:47Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
  Pgconfig Debug:
    Last Transition Time:  2023-02-13T15:11:44Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-13T15:11:43Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
  Profile Debug:
    Last Transition Time:  2023-02-13T15:11:44Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-13T15:11:42Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
  s3BackupConfigDebug:
    Last Transition Time:  2023-02-13T15:11:48Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-13T15:11:46Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
  s3BucketDebug:
    Last Transition Time:  2023-02-13T15:11:42Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-02-13T15:11:47Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Secret Debug:
    Last Transition Time:  2023-02-13T15:12:07Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-02-13T15:12:13Z
    Reason:                Available
    Status:                True
    Type:                  Ready
```

If there are any issues with your instance, they will be mentioned in the status fields.

