name: Build and Deploy

on:
  push:

env:
  REGISTRY: registry.cloudscale-lpg-2.appuio.cloud
  PROJECT_NAME: vshn-docs
  SITE_IMAGE: registry.cloudscale-lpg-2.appuio.cloud/vshn-docs/appcat-user-main:latest
  SEARCH_IMAGE: registry.cloudscale-lpg-2.appuio.cloud/vshn-docs/appcat-user-search:latest

jobs:
  build:
    name: Build Antora Site 🏗️
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Antora Site
        uses: redhat-actions/buildah-build@v2
        with:
          tags: ${{ env.SITE_IMAGE }}
          containerfiles: |
            ./deployment/main/Containerfile

      - name: Build Antora Search Index
        uses: redhat-actions/buildah-build@v2
        with:
          tags: ${{ env.SEARCH_IMAGE }}
          containerfiles: |
            ./deployment/search/Containerfile

      - name: Log in to APPUiO Cloud registry
        uses: redhat-actions/podman-login@v1
        with:
          username: serviceaccount
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ env.REGISTRY }}

      - name: Push Antora Site Image
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ env.SITE_IMAGE }}

      - name: Push Search Image
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ env.SEARCH_IMAGE }}

  deploy:
    name: Deploy Antora Site 🚀
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "latest"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.PROJECT_NAME }}

      - name: Apply Manifests
        run: |
          sed -i "s/GITSHAFULL/$GITHUB_SHA/" deployment/deployment.yaml
          oc apply -f deployment/
